// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The **satori_dac_deployment_settings** data source allows finding DAC deployment settings by it's ID.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as satori from "@pulumi/satori";
 *
 * const dataaccessControllerId = "<assigned dataaccess_controller_id>";
 * const deploymentSettings = satori.getDacDeploymentSettings({
 *     id: dataaccessControllerId,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getDacDeploymentSettings(args: GetDacDeploymentSettingsArgs, opts?: pulumi.InvokeOptions): Promise<GetDacDeploymentSettingsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("satori:index/getDacDeploymentSettings:getDacDeploymentSettings", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getDacDeploymentSettings.
 */
export interface GetDacDeploymentSettingsArgs {
    /**
     * DAC's id.
     */
    id: string;
}

/**
 * A collection of values returned by getDacDeploymentSettings.
 */
export interface GetDacDeploymentSettingsResult {
    /**
     * DAC's id.
     */
    readonly id: string;
    /**
     * The DAC's deployments service account
     */
    readonly serviceAccount: string;
}
/**
 * The **satori_dac_deployment_settings** data source allows finding DAC deployment settings by it's ID.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as satori from "@pulumi/satori";
 *
 * const dataaccessControllerId = "<assigned dataaccess_controller_id>";
 * const deploymentSettings = satori.getDacDeploymentSettings({
 *     id: dataaccessControllerId,
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getDacDeploymentSettingsOutput(args: GetDacDeploymentSettingsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDacDeploymentSettingsResult> {
    return pulumi.output(args).apply((a: any) => getDacDeploymentSettings(a, opts))
}

/**
 * A collection of arguments for invoking getDacDeploymentSettings.
 */
export interface GetDacDeploymentSettingsOutputArgs {
    /**
     * DAC's id.
     */
    id: pulumi.Input<string>;
}
