// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the satori package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'satori';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Your Satori account ID.
     */
    public readonly satoriAccount!: pulumi.Output<string>;
    /**
     * Service account ID with administrative privileges. Can be specified with the `SATORI_SA` environment variable.
     */
    public readonly serviceAccount!: pulumi.Output<string | undefined>;
    /**
     * Service account key. Can be specified with the `SATORI_SA_KEY` environment variable.
     */
    public readonly serviceAccountKey!: pulumi.Output<string | undefined>;
    public readonly url!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.satoriAccount === undefined) && !opts.urn) {
                throw new Error("Missing required property 'satoriAccount'");
            }
            resourceInputs["satoriAccount"] = args ? args.satoriAccount : undefined;
            resourceInputs["serviceAccount"] = args ? args.serviceAccount : undefined;
            resourceInputs["serviceAccountKey"] = args?.serviceAccountKey ? pulumi.secret(args.serviceAccountKey) : undefined;
            resourceInputs["url"] = (args ? args.url : undefined) ?? (utilities.getEnv("SATORI_URL") || "https://app.satoricyber.com");
            resourceInputs["verifyTls"] = pulumi.output(args ? args.verifyTls : undefined).apply(JSON.stringify);
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["serviceAccountKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Your Satori account ID.
     */
    satoriAccount: pulumi.Input<string>;
    /**
     * Service account ID with administrative privileges. Can be specified with the `SATORI_SA` environment variable.
     */
    serviceAccount?: pulumi.Input<string>;
    /**
     * Service account key. Can be specified with the `SATORI_SA_KEY` environment variable.
     */
    serviceAccountKey?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
    verifyTls?: pulumi.Input<boolean>;
}
